name: Azure Static Web Apps CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main

jobs:
    build_and_deploy_job:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
                  lfs: false
            - name: Install Bun
              run: |
                  curl -fsSL https://bun.sh/install | bash
                  echo 'export BUN_INSTALL="$HOME/.bun"' >> $GITHUB_ENV
                  echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV
            - name: Install dependencies
              run: bun install
              env:
                  BUN_INSTALL: ${{ env.BUN_INSTALL }}
                  PATH: ${{ env.BUN_INSTALL }}/bin:${{ env.PATH }}
              working-directory: ./packages # Adjust this if your package.json is in a different directory
            - name: Build the application
              run: bun build
              env:
                  BUN_INSTALL: ${{ env.BUN_INSTALL }}
                  PATH: ${{ env.BUN_INSTALL }}/bin:${{ env.PATH }}
              working-directory: ./packages # Adjust this if necessary
            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_RIVER_01D77C50F }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: 'upload'
                  app_location: './packages' # App source code path
                  api_location: '' # Api source code path - optional
                  output_location: 'build' # Built app content directory (adjust if your build output directory is different)

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_RIVER_01D77C50F }}
                  action: 'close'
